
(()=>{const C=window.BEING_KONSULTASI_CONFIG||{},$=s=>document.querySelector(s),E=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));const SERVICES=[
["KLINIS","Layanan Klinis","Penerapan modalitas terapi spesifik, Motivational Interviewing, CBT untuk adiksi, 12-Step, manajemen kasus komorbiditas, dan area klinis terkait."],
["ETIKA","Dilema etika, aspek hukum, dan batasan profesional (boundaries)","Pembahasan etika, aspek hukum, batas profesional, dan pengambilan keputusan profesional."],
["ASESMEN","Pengembangan keterampilan asesmen dan alat tes baru","Pengembangan kompetensi asesmen dan penggunaan alat tes baru."],
["COUNTER","Pengelolaan emosi pribadi akibat paparan cerita klien (countertransference)","Ruang pengelolaan emosi pribadi dan refleksi profesional akibat paparan cerita klien."],
["ADMIN","Administrasi klinis (penulisan rekam medis, laporan, atau rujukan)","Penulisan rekam medis, laporan, atau rujukan."],
["REHAB","Tata kelola Rehabilitasi sesuai standart","Pembahasan tata kelola rehabilitasi sesuai standar."],
["KARIR","Tata kelola Karir (menuju kompetensi)","Pendampingan tata kelola karir menuju kompetensi."]
];function msg(t,c="notice"){if($("#msg"))$("#msg").innerHTML=`<div class="notice ${c}">${E(t)}</div>`}
async function api(action,payload={}){if(!C.API_URL||C.API_URL.includes("PASTE_"))throw Error("API Konsultasi belum dihubungkan di config.js.");const r=await fetch(C.API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action,payload})}),j=await r.json();if(!j.ok)throw Error(j.message||"Permintaan gagal.");return j}
function render(){if($("#services"))$("#services").innerHTML=SERVICES.map(s=>`<label class="service"><input type="checkbox" name="service" value="${s[0]}"><b>${E(s[1])}</b><p>${E(s[2])}</p></label>`).join("")}
async function submit(){const d={nama:$("#nama").value.trim(),email:$("#email").value.trim(),wa:$("#wa").value.trim(),instansi:$("#instansi").value.trim()};if(!d.nama||!d.email||!d.wa)throw Error("Nama, email, dan WhatsApp wajib diisi.");const c=await api("client.register",d),ids=[...document.querySelectorAll('input[name="service"]:checked')].map(x=>x.value),m=document.querySelector('input[name="method"]:checked')?.value,n=m==="KELOMPOK"?Number($("#jumlahPeserta").value||1):1;if(!ids.length)throw Error("Pilih minimal satu layanan.");if(!m)throw Error("Pilih metode.");if(m==="KELOMPOK"&&(n<1||n>9))throw Error("Jumlah peserta kelompok maksimal 9 orang.");sessionStorage.setItem("beingKonsultasiClient",JSON.stringify(c.client));await api("consultation.submit",{clientId:c.client.clientId,serviceIds:ids,method:m,jumlahPeserta:n,catatan:$("#catatan").value.trim()});location.href="dashboard.html"}
async function history(){let c;try{c=JSON.parse(sessionStorage.getItem("beingKonsultasiClient")||"null")}catch(_){}if(!c){msg("Silakan daftar sebagai klien terlebih dahulu.","error");return}$("#clientName").textContent=c.nama;const r=await api("client.history",{clientId:c.clientId});$("#history").innerHTML=(r.items||[]).map(x=>`<a class="card item" href="detail.html?id=${encodeURIComponent(x.konsultasiId)}"><b>${E(x.konsultasiId)}</b><div>${E(x.layananNama)}</div><div class="muted">${E(x.method)} · ${E(x.status)}</div></a>`).join("")||'<div class="muted">Belum ada pengajuan.</div>'}
async function detail(){let c;try{c=JSON.parse(sessionStorage.getItem("beingKonsultasiClient")||"null")}catch(_){}const id=new URLSearchParams(location.search).get("id");if(!c||!id)throw Error("Pengajuan tidak ditemukan.");const r=await api("consultation.detail",{clientId:c.clientId,konsultasiId:id}),x=r.consultation;$("#detail").innerHTML=`<h2>${E(x.konsultasiId)}</h2><p><b>Layanan:</b> ${E(x.layananNama)}</p><p><b>Metode:</b> ${E(x.method)}</p><div class="steps">${["PENGAJUAN BARU","DISETUJUI","MENUNGGU PEMBAYARAN","MENUNGGU VERIFIKASI","LUNAS","TERJADWAL","SELESAI"].map(s=>`<div class="step ${s===x.status||s===x.statusPembayaran?"on":""}">${s}</div>`).join("")}</div>${x.status==="DISETUJUI"&&x.statusPembayaran==="MENUNGGU_PEMBAYARAN"?`<div class="notice"><b>Pembayaran tersedia.</b><br>Instruksi rekening/QRIS dikirim melalui email BEING.<br><a class="btn" href="payment.html?id=${encodeURIComponent(id)}">Kirim Bukti Pembayaran</a></div>`:""}${x.statusPembayaran==="MENUNGGU_VERIFIKASI"?'<div class="notice success">Bukti pembayaran sedang diverifikasi admin.</div>':""}${x.psikolog?`<div class="card"><b>Psikolog</b><p>${E(x.psikolog)}</p><b>Jadwal</b><p>${E(x.jadwal||"Menunggu penetapan")}</p></div>`:""}`}
async function proof(){let c;try{c=JSON.parse(sessionStorage.getItem("beingKonsultasiClient")||"null")}catch(_){}const id=new URLSearchParams(location.search).get("id"),f=$("#proof").files[0];if(!c||!id||!f)throw Error("Pilih bukti pembayaran.");const b=new Uint8Array(await f.arrayBuffer());let s="";for(const x of b)s+=String.fromCharCode(x);const r=await api("payment.proof",{clientId:c.clientId,konsultasiId:id,fileName:f.name,mimeType:f.type,fileData:btoa(s),catatan:$("#paymentNote").value.trim()});msg(r.message,"success")}
document.addEventListener("DOMContentLoaded",()=>{render();document.querySelectorAll('input[name="method"]').forEach(x=>x.addEventListener("change",()=>$("#groupCount")?.classList.toggle("hidden",x.value!=="KELOMPOK")));$("#form")?.addEventListener("submit",e=>{e.preventDefault();submit().catch(x=>msg(x.message,"error"))});if($("#history"))history().catch(x=>msg(x.message,"error"));if($("#detail"))detail().catch(x=>msg(x.message,"error"));$("#paymentForm")?.addEventListener("submit",e=>{e.preventDefault();proof().catch(x=>msg(x.message,"error"))})})})();
